drop table "AspNetRoleClaims" cascade; 
drop table "AspNetRoles" cascade; 
drop table "AspNetUserClaims" cascade; 
drop table "AspNetUserLogins" cascade; 
drop table "AspNetUserRoles" cascade; 
drop table "AspNetUserTokens" cascade; 
drop table "AspNetUsers" cascade; 
drop table "Avatars" cascade; 
drop table "Comments" cascade; 
drop table "Courses" cascade; 
drop table "Ratings" cascade; 
drop table "Solutions" cascade;
drop table "SolutionsVersions" cascade;
drop table "Tasks" cascade;
drop table "Tasksets" cascade;
drop table "Files" cascade;
drop table "SolutionsFiles" cascade;
drop table "Tags" cascade;
drop table "Tags_Id_seq";
drop table "TasksFiles";
drop table "TasksetsFiles";

drop table "__EFMigrationsHistory" cascade;